# Generated by Django 5.1 on 2024-08-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepalarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='zero_offset',
            field=models.FloatField(),
        ),
    ]
