# Generated by Django 5.1 on 2024-08-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepalarm', '0002_alter_scale_zero_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='step_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scale',
            name='zero_offset',
            field=models.FloatField(null=True),
        ),
    ]
